jumps: 86400
start_date: "2020-08-11"
end_date: "2025-06-28"
root: "./data"
date_format: "%Y-%m-%d"
data_path: "./data/sol_one_day_pred.csv"  # 修改为 SOL 数据文件
train_interval: ["2020-08-11", "2023-12-31"]
val_interval: ["2024-01-01", "2024-10-31"]
test_interval: ["2024-11-01", "2025-06-28"]
additional_features: []
