jumps: 86400
start_date: "2019-07-17"
end_date: "2025-06-17"
root: "./data"
date_format: "%Y-%m-%d"
data_path: "./data/Dataset_daily.csv"
train_interval: ["2019-07-17", "2023-07-17"]
val_interval: ["2023-07-17", "2024-07-17"]
test_interval: ["2024-07-17", "2025-06-17"]
additional_features: []
